server:
  port: 5555
  # Removed context-path because Nginx is likely stripping the /rest prefix
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    oauth:
      app-name: SNPSeek API Server
      realm: snpseek_realm
      auth-url: https://brs-snpseek.duckdns.org/auth/realms/snpseek_realm/protocol/openid-connect/auth
      token-url: https://brs-snpseek.duckdns.org/auth/realms/snpseek_realm/protocol/openid-connect/token
      client-id: snpseek-api-client
      use-pkce-with-authorization-code-grant: true
      scopes: openid
  servers:
    - url: ${APP_PUBLIC_URL:https://brs-snpseek.duckdns.org/rest}
      description: Production Server

app:
  public-url: ${APP_PUBLIC_URL:https://brs-snpseek.duckdns.org/rest}

spring:
  application:
    name: SNPSeek-API-Server
  
  # PostgreSQL Configuration
  datasource:
    url: ${DB_URL}
    username:  ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    
    # Connection pool settings (HikariCP)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # SECURITY CONFIG (Keycloak)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://brs-snpseek.duckdns.org/auth/realms/snpseek_realm
          jwk-set-uri: https://brs-snpseek.duckdns.org/auth/realms/snpseek_realm/protocol/openid-connect/certs
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true

bucket4j:
  methods:
    - filter-order: 1
      execute-condition: "true"
      cache-name: buckets
      rate-limit:
        - bandwidths:
          - capacity: 5
            time: 1
            unit: minutes
            strategy: first
            key-source: IP

logging:
  level:
    org.springframework.web: INFO
    org.irri.snpseek: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
